---
title: "BRI_Page"
author: "Cian Stryker"
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# So I'm loading in the packages I need again. 

library(readxl)
library(reshape2)
library(plyr)
library(countrycode)
library(janitor)
library(jtools)
library(kableExtra)
library(gvlma)
library(maps)
library(png)
library(cowplot)
library(reprex)
library(ggrepel)
library(gganimate)
library(tidyverse)
```

```{r, Chinese FDI Loading, message=FALSE}

# I use Message=FALSE because I 
# didn't know how to fix the errors.

# This is the data I need again and I'm just cleaning it up for work.

Chinese_FDI <- read_excel("raw-data/Chinese_Investment_and_Construction.xlsx", skip = 4) %>%
  clean_names()

# Time to get the country names to be uniform and rename columns.

Chinese_FDI$country <- countrycode(Chinese_FDI$country, "country.name", "country.name")
Chinese_FDI$country2 = Chinese_FDI$country

# I want the abreviated country names as well.

Chinese_FDI$country2 <- countrycode(Chinese_FDI$country2, "country.name", "iso2c")
```

```{r, Mapwold loading, warning=FALSE}

# I use warning=FALSE because I 
# didn't know how to fix the errors.

# The map packages is great and I'm using it again on this tab.
# I'm also renaiming columns to make life easier. 

map.world <- map_data('world')
colnames(map.world)[colnames(map.world) == 'region'] <- 'country'
map.world$country <- countrycode(map.world$country, "country.name", "country.name")

```

```{r, Commulative BRI graph by Target Region}

# Alright to start I just grab the BRI regions and BRI investment sectors

China_sector4 <- Chinese_FDI %>%
    select("country", "region", "year", "sector", "quantity_in_millions") %>%
    filter(sector %in% c("Energy", "Real estate", "Metals", "Transport")) %>%
    filter(region %in% c("Arab Middle East and North Africa", 
                         "East Asia", 
                         "South America", 
                         "Sub-Saharan Africa", 
                         "West Asia"))

# Then I aggregate the investments per year, country, region, and sector.

China_sector4x <- aggregate(quantity_in_millions ~ country 
                            + year 
                            + region 
                            + sector, 
                            data = China_sector4, 
                            FUN = sum)

# Then I nest those amounts per year,  create my sums, and then filter for 2019.

China_sector4y <- China_sector4x %>%
  complete(year, nesting(country, region, sector), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(region, country, sector) %>%
  mutate(y_cum3 = cumsum(quantity_in_millions)) %>%
  mutate(FDI = y_cum3 * 1000000) %>%
  filter(year == 2019)

# Here I just make my bar shart for FDI faceted per BRI region.

plot5 <- ggplot(China_sector4y, aes(x = sector, y = FDI, fill = region)) +
  geom_col()+
  labs(x= "Sector", y= "Foreign Direct Investment", fill=NULL, title="Chinese BRI Investment") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 12)) +
  guides(fill = FALSE) +
  facet_wrap(~region)

```

```{r, Map 2 Setup}

# Now I grab what I need, including abbreviated country names
# and then also filter for the BRI regions. 

China2 <- Chinese_FDI %>% 
    select("year", `quantity_in_millions`, "country", "region", "country2") %>%
    filter(region %in% c("West Asia", 
                         "South America",
                         "Arab Middle East and North Africa",
                         "Sub-Saharan Africa",
                         "East Asia"
                          ))

# Now I'm just aggregating everything again. 

China2_x <- aggregate(quantity_in_millions ~ country + 
                        year + 
                        region + 
                        country2, 
                        data = China2, 
                        FUN = sum)
```


```{r, Map 2 combination}

# Now I'm nesting, finding cummulatives, and filterring for 2019. 
# This is similar to the code before but now for different things. 

trial <- China2_x %>%
  complete(year, nesting(country, region), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(region, country) %>%
  mutate(y_cum = cumsum(quantity_in_millions)) %>%
  mutate(FDI = y_cum * 1000000) %>%
  filter(year == 2019)
  
# Here a left_join lets me combine this data with the world map. 

workss2 <- left_join(map.world, trial, by = c("country"))

``` 

```{r, Map 2 only Target Reion, warning=FALSE}

# I use warning=FALSE because I 
# didn't know how to fix the errors.


# This is just another world map chunk. It's essentially a lot of detail work
# but I explained most of it in the 'About_Page' so see those comments for
# more details. 

plot6 <- ggplot(workss2, aes( x = long, y = lat, group = group )) +
  geom_polygon(aes(fill = FDI)) +
  guides(fill = guide_legend(reverse = T,)) +
  scale_fill_gradientn(colours = c('#461863','#404E88','#2A8A8C','#7FD157','#F9E53F'), 
                       values = scales::rescale(c(0,1e+10, 2e+10, 3e+10, 4e+10, 6e+10)), 
                       breaks = c(0,1e+10, 2e+10, 3e+10, 4e+10, 6e+10)
                       ) +
  labs(fill = 'Commulative FDI
in USD',
       title = 'Commulative BRI Chinese Foreign Direct Investment by Country',
       subtitle = '2019',
       x = NULL,
       y = NULL) +
  theme(text = element_text(color = '#333333'),
        plot.title = element_text(size = 18),
        plot.subtitle = element_text(size = 14),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.background = element_rect(fill = '#CCCCCC'),
        legend.position = c(.18,.36),
        legend.background = element_rect(fill = '#CCCCCC'),
        legend.key = element_blank()
        ) +
  annotate(geom = 'text',
           label = 'Source: The American Enterprise Institute and The Heritage Foundation',
           x = 18, y = -55,
           size = 3,
           color = '#333333',
           hjust = 'left'
           )
```

```{r, BRI per Country Scatter Graph}

# This is the data set up for my slider graph in shiny. 
# I want to show FDI per country over time in this graph, 
# so I just grab what I need and create my FDI sums

data7 <- China2_x %>%
  complete(year, nesting(country2, region), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(region, country2) %>%
  mutate(y_cum = cumsum(quantity_in_millions)) %>%
  mutate(FDI = y_cum * 1000000) 

```

```{r, Highest BRI Investment Countries Labelled Scatter}

# To make my last graph here I'm doing exactly what I did 
# before I'm nesting, grouping, creating the cummulative amount, 
# and then mutating FDI to make more sense numerically.

trial2x <- China2_x %>%
  complete(year, nesting(country, region), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(region, country) %>%
  mutate(y_cum = cumsum(quantity_in_millions)) %>%
  mutate(FDI = y_cum * 1000000) 

# Now I just ungroup, and filter for what I want, which happens
# to be 2019 and only countries with FDI above a certain point.

trial3 <- trial2x %>%
  ungroup() %>%
  filter(year == 2019) %>%
  filter(FDI >= 1.5e+10) %>%
  select("year", "region", "country", "FDI")

# Finally I plot this with labels included via ggrepel, 
# which is great for automatically placing visible label
# names. 

plot8 <- ggplot(trial3, aes(x = country, y = FDI, color = region)) +
  geom_point()+
  geom_label_repel(aes(label = country),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  label.size = 0,
                  segment.color = 'grey50') +
  labs(x= "Countries", y="Foreign Direct Investment", fill= NULL, title="Top BRI Investment Countries") +
  theme_bw() +
  expand_limits(y = 80000) +
  guides(color= FALSE) +
  theme(axis.text.x=element_blank()) +
  facet_wrap(~region)

```