---
title: "BRI_Effects"
author: "Cian Stryker"
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(reshape2)
library(plyr)
library(countrycode)
library(janitor)
library(gvlma)
library(maps)
library(png)
library(cowplot)
library(reprex)
library(ggrepel)
library(gganimate)
library(tidyverse)
```

```{r, Chinese FDI Loading, message=FALSE}
Chinese_FDI <- read_excel("raw-data/Chinese_Investment_and_Construction.xlsx", skip = 4) %>%
  clean_names()

Chinese_FDI$country <- countrycode(Chinese_FDI$country, "country.name", "country.name")
Chinese_FDI$country2 = Chinese_FDI$country

Chinese_FDI$country2 <- countrycode(Chinese_FDI$country2, "country.name", "iso2c")
```

```{r, Freedom House Loading, include=FALSE}
PR <- read_excel("raw-data/PR.xlsx")

Pr_1 <- melt(PR, measure.vars = 2:15) 

colnames(Pr_1)[colnames(Pr_1) == 'variable'] <- 'year'
colnames(Pr_1)[colnames(Pr_1) == 'value'] <- 'PR'
colnames(Pr_1)[colnames(Pr_1) == 'Country'] <- 'country'


Pr_1$country <- countrycode(Pr_1$country, "country.name", "country.name")


Pr_2 <- Pr_1 %>%  
    mutate(PR = as.numeric(PR))
```

```{r, GDP loading, message=FALSE, warning=FALSE}
GDP_An <- read_excel("raw-data/GDP.xls", skip = 2) 
 
GDP2 <- melt(GDP_An, measure.vars = 2:15) %>%
  clean_names()

colnames(GDP2)[colnames(GDP2) == 'variable'] <- 'year'
colnames(GDP2)[colnames(GDP2) == 'value'] <- 'GDP_Increase'
colnames(GDP2)[colnames(GDP2) == 'country_name'] <- 'country'

GDP2$country <- countrycode(GDP2$country, "country.name", "country.name") 
GDP2$country2 = GDP2$country

GDP2$country2 <- countrycode(GDP2$country2, "country.name", "iso2c")

GDP_Final <- na.omit(GDP2)
```

```{r, Mapwold loading, warning=FALSE}

map.world <- map_data('world')
colnames(map.world)[colnames(map.world) == 'region'] <- 'country'
map.world$country <- countrycode(map.world$country, "country.name", "country.name")

```

```{r}
test99 <- Chinese_FDI %>%
  select("country2", "quantity_in_millions", "year") 

test29 <- aggregate(quantity_in_millions ~ country2 + year, data = test99, FUN = sum)

test39 <- test29 %>%
  complete(year, nesting(country2), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(country2) %>%
  mutate(y_cum4 = cumsum(quantity_in_millions))

test49 <- merge(test39, GDP_Final, by = c("year", "country2")) %>%
  filter(year == 2018) %>%
  filter(GDP_Increase <= 1.0e+13 )

ggplot(test49, aes(x = y_cum4,  y = GDP_Increase)) +
   geom_point() +
   geom_smooth(method = "lm", se = FALSE) 

linearMod <- lm(y_cum4 ~ GDP_Increase, data=test49)  
print(linearMod)
summary(linearMod)

gvlma::gvlma(linearMod)
```

```{r, BRI and GDP Scatter Plot }
test <- Chinese_FDI %>%
  select("country2", "quantity_in_millions", "year","sector", "region") %>%
  filter(region %in% c("Arab Middle East and North Africa", "East Asia", "South America", "Sub-Saharan Africa", "West Asia")) %>%
  filter(sector %in% c("Energy", "Real estate", "Metals", "Transport")) 

test2 <- aggregate(quantity_in_millions ~ country2 + year + region, data = test, FUN = sum)

test3 <- test2 %>%
  complete(year, nesting(country2, region), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(region, country2) %>%
  mutate(y_cum4 = cumsum(quantity_in_millions))

test4 <- merge(test3, GDP_Final, by = c("year", "country2")) 

ggplot(test4, aes(x = y_cum4, size = y_cum4, color = region, y = GDP_Increase)) +
  geom_point() +
  geom_text(data = subset(test4, y_cum4 > 30000 | GDP_Increase > 1e+12), aes(label = country2, hjust = 0, vjust = -1.3)) +
  labs(x=NULL, y=NULL, fill=NULL, title="Year {closest_state}") +
  transition_states(year, transition_length = 4, state_length = 4) +
  enter_fade() +
  guides(size = FALSE, color = FALSE) +
  ease_aes('sine-in-out')+
  facet_wrap(~region)
```
```{r}
test5 <- test4 %>%
  filter(year == 2018)

ggplot(test5, aes(x = y_cum4, size = y_cum4, color = region, y = GDP_Increase)) +
   geom_point() +
   geom_smooth(method = "lm", se = FALSE) + 
  geom_text(data = subset(test5, y_cum4 > 20000), aes(label = country2, hjust = 1.3, vjust = 1)) +
  labs(x=NULL, y=NULL, fill=NULL, title= "Commulative FDI with GDP in 2019") +
  guides(size = FALSE, color = FALSE) +
  facet_wrap(~region)
```
```{r}
test_5 <- test4 %>%
  filter(year == 2018) %>%
  filter(region == "East Asia") %>%
  filter(GDP_Increase <= 1.4e+12)

ggplot(test_5, aes(x = y_cum4, y = GDP_Increase)) +
   geom_point() +
   geom_smooth(method = "lm", se = FALSE) 


linearMod2 <- lm(y_cum4 ~ GDP_Increase, data=test_5)  
print(linearMod)
summary(linearMod2)

gvlma::gvlma(linearMod2)
```

```{r, BRI and Political Rights Bar Graph}
x <- Chinese_FDI %>%
  select("year", "quantity_in_millions","region", "country") 

x2 <- x %>%
    filter(region %in% c("Arab Middle East and North Africa", "East Asia", "South America", "Sub-Saharan Africa", "West Asia"))

x3 <- aggregate(quantity_in_millions ~ country + year + region, data = x2, FUN = sum) 


x4 <-x3 %>%
  complete(year, nesting(country, region), fill = list(quantity_in_millions=0)) %>%
  arrange(year) %>%
  group_by(region, country) %>%
  mutate(y_cum5 = cumsum(quantity_in_millions))

x5 <- merge(x4, Pr_1, by = c("year", "country")) %>%
  filter(PR %in% c("1", "2", "3", "4", "5", "6", "7")) %>%
  group_by(PR)

ggplot(x5, aes(x = PR, y = y_cum5, fill = PR)) + 
  geom_col() +
  labs(x="Politcal Rights", y="Cummulative FDI", fill=NULL, title="Year {closest_state}") +
  transition_states(year, transition_length = 4, state_length = 4) +
  enter_fade() +
  guides(size = FALSE) +
  ease_aes('sine-in-out')
``` 

```{r, PR Map}

Map1 <- x5 %>%
  filter(year == 2005)

Map1x <- left_join(map.world, Map1, by = c("country"))

Map2 <- x5 %>%
  filter(year == 2018)

Map2x <- left_join(map.world, Map2, by = c("country"))

```

```{r}
x6 <- merge(x4, Pr_2, by = c("year", "country")) %>%
  filter(PR %in% c("1", "2", "3", "4", "5", "6", "7")) %>%
  group_by(PR)

linearMod3 <- lm(y_cum5 ~ PR, data=x6)  
print(linearMod3)
summary(linearMod3)

gvlma::gvlma(linearMod3)
```

```{r, warning=FALSE}

ggplot(Map1x, aes( x = long, y = lat, group = group )) +
  geom_polygon(aes(fill = PR)) +
  guides(fill = guide_legend(reverse = T,)) +
  scale_fill_discrete() +
  labs(fill = 'Political Rights'
       ,title = 'Political Rights within the BRI Regions'
       ,subtitle = '2005'
       ,x = NULL
       ,y = NULL) +
  theme(text = element_text(family = 'Gill Sans', color = '#333333')
        ,plot.title = element_text(size = 18)
        ,plot.subtitle = element_text(size = 14)
        ,axis.ticks = element_blank()
        ,axis.text = element_blank()
        ,panel.grid = element_blank()
        ,plot.background = element_rect(fill = '#CCCCCC')
        ,legend.position = c(.18,.36)
        ,legend.background = element_rect(fill = '#CCCCCC')
        ,legend.key = element_blank()
        ) +
  annotate(geom = 'text'
           ,label = 'Source: Freedom House'
           ,x = 18, y = -55
           ,size = 3
           ,family = 'Gill Sans'
           ,color = '#333333'
           ,hjust = 'left'
           )
```

```{r, warning=FALSE}

ggplot(Map2x, aes( x = long, y = lat, group = group )) +
  geom_polygon(aes(fill = PR)) +
  guides(fill = guide_legend(reverse = T,)) +
  scale_fill_discrete() +
  labs(fill = 'Political Rights'
       ,title = 'Political Rights within the BRI Regions'
       ,subtitle = '2018'
       ,x = NULL
       ,y = NULL) +
  theme(text = element_text(family = 'Gill Sans', color = '#333333')
        ,plot.title = element_text(size = 18)
        ,plot.subtitle = element_text(size = 14)
        ,axis.ticks = element_blank()
        ,axis.text = element_blank()
        ,panel.grid = element_blank()
        ,plot.background = element_rect(fill = '#CCCCCC')
        ,legend.position = c(.18,.36)
        ,legend.background = element_rect(fill = '#CCCCCC')
        ,legend.key = element_blank()
        ) +
  annotate(geom = 'text'
           ,label = 'Source: Freedom House'
           ,x = 18, y = -55
           ,size = 3
           ,family = 'Gill Sans'
           ,color = '#333333'
           ,hjust = 'left'
           )
```